* [32mmain[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/develop[m
  [31mremotes/origin/feacture/login[m
  [31mremotes/origin/feature/administracion[m
  [31mremotes/origin/feature/citas[m
  [31mremotes/origin/feature/dbclinica[m
  [31mremotes/origin/feature/frontend1[m
  [31mremotes/origin/feature/frontend2[m
  [31mremotes/origin/feature/medicos[m
  [31mremotes/origin/feature/pacientes[m
  [31mremotes/origin/feature/reportes[m
  [31mremotes/origin/main[m
  [31mremotes/origin/refactor/basede-datos[m
